'use strict';
// Productos ilustrativos; no representan el inventario real.
window.HIPERCELL_PRODUCTS = Object.freeze([
  { id: 'demo-01', name: 'Pantalla de repuesto', category: 'Repuestos', price: 35, kind: 'screen', featured: true, available: true, short: 'Una nueva vida para tu pantalla.', description: 'Producto ilustrativo para definir la ficha de repuestos. En el catálogo final se indicarán el modelo compatible, la calidad de la pieza y sus características.' },
  { id: 'demo-02', name: 'Auriculares inalámbricos', category: 'Audio', price: 28, kind: 'audio', featured: true, available: true, short: 'Tu música, siempre contigo.', description: 'Producto de muestra. Las fotografías, autonomía, compatibilidad y especificaciones se completarán con los datos reales del negocio.' },
  { id: 'demo-03', name: 'Cargador USB-C', category: 'Carga', price: 18, kind: 'charger', featured: false, available: true, short: 'Energía para seguir conectado.', description: 'Ejemplo de accesorio de carga. Antes de publicar se confirmarán la potencia, los protocolos de carga y el contenido del paquete.' },
  { id: 'demo-04', name: 'Funda protectora', category: 'Accesorios', price: 8, kind: 'case', featured: false, available: true, short: 'Protección con personalidad.', description: 'Ejemplo de funda. En la versión final se mostrarán los modelos de teléfono compatibles, materiales y colores disponibles.' },
  { id: 'demo-05', name: 'Batería de repuesto', category: 'Repuestos', price: 22, kind: 'battery', featured: false, available: false, short: 'Más vida para tu dispositivo.', description: 'Producto de muestra marcado como agotado para revisar ese estado. Los datos de capacidad y compatibilidad están pendientes.' },
  { id: 'demo-06', name: 'Cable USB-C', category: 'Carga', price: 6, kind: 'cable', featured: false, available: true, short: 'Una conexión que te acompaña.', description: 'Ejemplo de cable de conexión. Longitud, conectores y capacidad de carga se definirán a partir del inventario real.' },
  { id: 'demo-07', name: 'Soporte de escritorio', category: 'Accesorios', price: 12, kind: 'stand', featured: false, available: true, short: 'Tu pantalla, en su lugar.', description: 'Ejemplo de soporte de escritorio. Las dimensiones y materiales mostrados en la versión final corresponderán al producto real.' },
  { id: 'demo-08', name: 'Altavoz portátil', category: 'Audio', price: 32, kind: 'speaker', featured: false, available: true, short: 'Lleva tu sonido más lejos.', description: 'Ejemplo de altavoz portátil. La potencia, conectividad y autonomía se completarán al incorporar los productos de Hipercell.' }
]);
