import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const business='46a2d035-836b-472c-9f1f-adcde294a923';
const other='11111111-1111-4111-8111-111111111111';
const owner='22222222-2222-4222-8222-222222222222';
const stranger='33333333-3333-4333-8333-333333333333';
await db.exec(`
 create role anon;create role authenticated;create role service_role;
 create schema auth;create schema storage;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function storage.foldername(text) returns text[] language sql immutable as $$select (string_to_array($1,'/'))[1:array_length(string_to_array($1,'/'),1)-1]$$;
 create table auth.users(id uuid primary key,email text unique);
 create table public.catalogo_negocios(id uuid primary key,nombre text);
 create table public.catalogo_usuarios_negocio(user_id uuid primary key references auth.users(id),negocio_id uuid references catalogo_negocios(id),rol text);
 create table public.catalogo_categorias(id bigint primary key,negocio_id uuid references catalogo_negocios(id),nombre text,activo boolean default true);
 create table public.catalogo_productos(id bigint primary key,negocio_id uuid references catalogo_negocios(id),categoria_id bigint references catalogo_categorias(id) on delete set null,activo boolean default true,imagen_url text,imagenes_url jsonb default '[]');
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id bigint generated always as identity,name text,bucket_id text references storage.buckets(id));
 insert into catalogo_negocios values('${business}','Hipercell'),('${other}','Otro negocio');
 insert into auth.users values('${owner}','hipercell@gmail.com'),('${stranger}','otro@example.test');
 insert into catalogo_usuarios_negocio values('${stranger}','${other}','admin');
 insert into catalogo_categorias values(1,'${business}','Repuestos',true),(2,'${other}','Otros',true);
 alter table catalogo_productos enable row level security;
 alter table catalogo_categorias enable row level security;
 alter table catalogo_usuarios_negocio enable row level security;
 alter table storage.objects enable row level security;
 create policy cat_owner_ve_vinculo on catalogo_usuarios_negocio for select using(user_id=auth.uid());
 create policy cat_owner_productos on catalogo_productos for all using(negocio_id in(select negocio_id from catalogo_usuarios_negocio where user_id=auth.uid())) with check(negocio_id in(select negocio_id from catalogo_usuarios_negocio where user_id=auth.uid()));
 create policy cat_public_productos on catalogo_productos for select using(activo=true);
 create policy cat_owner_categorias on catalogo_categorias for all using(negocio_id in(select negocio_id from catalogo_usuarios_negocio where user_id=auth.uid())) with check(negocio_id in(select negocio_id from catalogo_usuarios_negocio where user_id=auth.uid()));
 create policy cat_public_categorias on catalogo_categorias for select using(activo=true);
 create policy old_cat_auth on storage.objects for all using(bucket_id='catalogo_imagenes' and current_user='authenticated');
 grant usage on schema public,auth,storage to anon,authenticated;
 grant select,insert,update,delete on all tables in schema public,storage to anon,authenticated;
 grant usage,select on all sequences in schema storage to authenticated;
 create function public.catalogo_crear_negocio(p_user_id uuid,p_nombre text default 'Mi Negocio') returns uuid language plpgsql security definer as $$begin return gen_random_uuid();end$$;
`);
const migration=fs.readFileSync('supabase/04-proteger-hipercell.sql','utf8');
await db.exec(migration);await db.exec(migration);
await db.exec(fs.readFileSync('supabase/05-vincular-administrador.sql','utf8'));
await db.exec(fs.readFileSync('supabase/05-vincular-administrador.sql','utf8'));
const photos=['https://example.test/one.jpg','https://example.test/two.jpg','https://example.test/three.jpg'];
await db.query('insert into catalogo_productos(id,negocio_id,categoria_id,imagen_url,imagenes_url) values(10,$1,1,$2,$3)',[business,photos[0],JSON.stringify(photos)]);
await assert.rejects(db.query('update catalogo_productos set imagenes_url=$1 where id=10',[JSON.stringify([...photos,'https://example.test/four.jpg'])]),/hipercell_max_tres_fotos/);
for(const images of [{a:1},['javascript:alert(1)'],[photos[0],photos[0]],[{url:photos[0]}]]){
 await assert.rejects(db.query('update catalogo_productos set imagenes_url=$1 where id=10',[JSON.stringify(images)]),/hipercell_max_tres_fotos/);
}
await assert.rejects(db.query('update catalogo_productos set imagen_url=$1 where id=10',[photos[1]]),/hipercell_max_tres_fotos/);
await assert.rejects(db.query('update catalogo_productos set categoria_id=2 where id=10'),/categoría no pertenece/);
await assert.rejects(db.query('update catalogo_categorias set negocio_id=$1 where id=1',[other]),/No se puede mover/);
await db.query('insert into catalogo_productos(id,negocio_id,categoria_id,imagenes_url) values(20,$1,2,$2)',[other,JSON.stringify([...photos,'https://example.test/four.jpg'])]);
await db.exec(`set role authenticated;set request.jwt.claim.sub='${owner}';`);
await db.query('insert into storage.objects(name,bucket_id) values($1,$2)',[business+'/10/image.jpg','hipercell_imagenes']);
await assert.rejects(db.query('insert into storage.objects(name,bucket_id) values($1,$2)',[other+'/20/image.jpg','hipercell_imagenes']),/row-level security/);
assert.equal((await db.query("update storage.objects set name=name||'changed' returning id")).rows.length,0);
assert.equal((await db.query('delete from storage.objects returning id')).rows.length,0);
await db.exec(`set request.jwt.claim.sub='${stranger}';`);
await assert.rejects(db.query('insert into storage.objects(name,bucket_id) values($1,$2)',[business+'/10/hack.jpg','hipercell_imagenes']),/row-level security/);
assert.equal((await db.query('update catalogo_productos set activo=false where id=10 returning id')).rows.length,0);
await db.exec('reset role;');
await db.exec('set role anon;');
await assert.rejects(db.query('insert into storage.objects(name,bucket_id) values($1,$2)',[business+'/10/anon.jpg','hipercell_imagenes']),/permission denied|row-level security/);
await db.exec('reset role;');
await db.exec(fs.readFileSync('supabase/06-cerrar-alta-publica-opcional.sql','utf8'));
const privileges=await db.query("select has_function_privilege('anon','public.catalogo_crear_negocio(uuid,text)','execute') as anon,has_function_privilege('authenticated','public.catalogo_crear_negocio(uuid,text)','execute') as authenticated,has_function_privilege('service_role','public.catalogo_crear_negocio(uuid,text)','execute') as service");
assert.deepEqual(privileges.rows[0],{anon:false,authenticated:false,service:true});
await db.close();console.log('PASS: SQL executed twice in isolated PostgreSQL; photo limits, categories, tenant RLS, immutable photos, admin linkage and optional helper privileges');

